package freetype

/*
#cgo pkg-config: freetype2
#include <ft2build.h>
#include FT_FREETYPE_H
*/
import "C"

const (
	ENCODING_NONE      int = C.FT_ENCODING_NONE
	ENCODING_MS_SYMBOL int = C.FT_ENCODING_MS_SYMBOL
	ENCODING_UNICODE   int = C.FT_ENCODING_UNICODE
	ENCODING_SJIS      int = C.FT_ENCODING_SJIS
	ENCODING_GB2312    int = C.FT_ENCODING_GB2312
	ENCODING_BIG5      int = C.FT_ENCODING_BIG5
	ENCODING_WANSUNG   int = C.FT_ENCODING_WANSUNG
	ENCODING_JOHAB     int = C.FT_ENCODING_JOHAB

	/* for backwards compatibility */
	ENCODING_MS_SJIS    = ENCODING_SJIS
	ENCODING_MS_GB2312  = ENCODING_GB2312
	ENCODING_MS_BIG5    = ENCODING_BIG5
	ENCODING_MS_WANSUNG = ENCODING_WANSUNG
	ENCODING_MS_JOHAB   = ENCODING_JOHAB

	ENCODING_ADOBE_STANDARD int = C.FT_ENCODING_ADOBE_STANDARD
	ENCODING_ADOBE_EXPERT   int = C.FT_ENCODING_ADOBE_EXPERT
	ENCODING_ADOBE_CUSTOM   int = C.FT_ENCODING_ADOBE_CUSTOM
	ENCODING_ADOBE_LATIN_1  int = C.FT_ENCODING_ADOBE_LATIN_1
	ENCODING_OLD_LATIN_2    int = C.FT_ENCODING_OLD_LATIN_2
	ENCODING_APPLE_ROMAN    int = C.FT_ENCODING_APPLE_ROMAN
)
